### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by AFunDog** [idle-lab/AlienWar#2]
- 在我克隆到本地后，尝试启动却出现无法找到文件的错误
FileNotFoundError: [Errno 2] No such file or directory: 'data\\history score.txt'
在 score_board.py 15 - 19 行并没有检测文件是否存在
下面是我本地修改的代码
![PixPin_2024-12-28_18-25-04](https://github.com/user-attachments/assets/0345a0dd-246c-438c-b3a5-ef10160452d7)

- 在主界面停留一段时间后会出现
TypeError: 'float' object cannot be interpreted as an integer
是因为 randint 接收两个 int 参数，但传入的 `alien_crate_speed` 却是个 float 参数，所以在内部引发下面的错误
File "C:\Users\Zeng\AppData\Local\Programs\Python\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zeng\AppData\Local\Programs\Python\Python312\Lib\random.py", line 312, in randrange
    istop = _index(stop)
            ^^^^^^^^^^^^

**Comment by idle-lab** [comment]
那提个pr吧，老早以前写的了QAQ，麻烦你了

**Comment by AFunDog** [comment]
> 那提个pr吧，老早以前写的了QAQ，麻烦你了

真的可以吗，谢谢了
这还是我第一次在别人的项目里做贡献，感谢学长给我这个机会
